/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IStMTRGInterface extends ethers.utils.Interface {
  functions: {
    "shareToValue(uint256)": FunctionFragment;
    "valueToShare(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "shareToValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "valueToShare",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "shareToValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "valueToShare",
    data: BytesLike
  ): Result;

  events: {};
}

export class IStMTRG extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IStMTRGInterface;

  functions: {
    shareToValue(
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "shareToValue(uint256)"(
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    valueToShare(
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "valueToShare(uint256)"(
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  shareToValue(
    _share: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "shareToValue(uint256)"(
    _share: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  valueToShare(
    _value: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "valueToShare(uint256)"(
    _value: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    shareToValue(
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "shareToValue(uint256)"(
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    valueToShare(
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "valueToShare(uint256)"(
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    shareToValue(
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "shareToValue(uint256)"(
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    valueToShare(
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "valueToShare(uint256)"(
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    shareToValue(
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "shareToValue(uint256)"(
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    valueToShare(
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "valueToShare(uint256)"(
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
